version: "3.9"
services:
    img_postgres_db:
        container_name: container_db_postgres
        image: postgres:latest
        restart: always
        volumes: 
            - .:/central_db
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        networks:
            - library_net
    backend_service:
        container_name: container_backend
        restart: always
        build: ./library_back
        command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        volumes:
            - .:/back_db
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_HOST=img_postgres_db
            - POSTGRES_PORT=5432
        depends_on:
            - img_postgres_db
        networks:
            - library_net
    frontend_service:
        container_name: container_frontend
        restart: always
        build: ./library_front
        command: npm start
        ports:
            - "3000:3000"
        volumes:
            - .:/front_db
        depends_on:
            - img_postgres_db
        networks:
            - library_net
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - frontend_service
        networks: 
            - library_net
networks:
    library_net:
        driver: bridge